
function loadQuestions(){
  questions = [
    {q: "Ułóż alfabetycznie:",
     a: ["a",
         "b",
         "c",
         "d",
         "e",
         "f",
         "g",
         "h"]},
    {q: "Ułóż alfabetycznie:",
     a: ["ą",
         "ć",
         "ę",
         "ł",
         "ń",
         "ó",
         "ś",
         "ż",
         "ź"]},
    {q: "Ułóż alfabetycznie:",
     a: ["abakus",
         "abażur",
         "abdukcja",
         "abdykacja",
         "abnegacja",
         "abominacja",
         "abrewiacja",
         "aglomeracja",
         "agregacja",
         "agronomia"]},
    {q: "Ułóż obiekty od największego do najmniejszego:",
     a: ["Wszechświat",
         "Grupa Lokalna",
         "Droga Mleczna",
         "Słońce",
         "Jowisz",
         "Saturn",
         "Ziemia",
         "Merkury",
         "Księżyc",
         "Pluton",
         "Fobos",
         "Mount Everest",
         "Piramida cheopsa",
         "British Museum",
         "Płetwal Błękitny",
         "słoń",
         "Dawid Michała Anioła",
         "żubr",
         "człowiek",
         "wilk",
         "kot",
         "jeż",
         "żaba",
         "kwiat stokrotki",
         "pszczoła",
         "mrówka",
         "ameba",
         "bakteria",
         "atom żelaza",
         "atom helu",
         "elektron",
         "kwark dolny"]},
    {q: "Ułóż warstwy od najbliższej do najdalszej od centrum ziemi:",
     a: ["jądro",
         "płaszcz",
         "skorupa",
         "atmosfera"]},
    {q: "Ułóż obiekty od najbliższego do najdalszego od Słońca:",
     a: ["Korona Słoneczna",
         "Merkury",
         "Wenus",
         "Ziemia",
         "Mars",
         "Pas planetoid",
         "Jowisz",
         "Saturn",
         "Uran",
         "Neptun",
         "Pluton",
         "Obłok Oorta",
         "Proxima Centauri",
         "Mgławica kraba",
         "Wielki Obłok Magellana",
         "Andromeda"]}
  ]
}
